### PR TITLE
Make tire.ajax return a Q promise if it detects Q

### PR DESCRIPTION
**Pull request by smcmurray**
If success or error callbacks are defined in options, they are invoked before the promise is fulfilled.
The promise will resolve to xhr or to the return value of the success callback.
If the promise is rejected, the reason should be an object with `reason` and `xhr` properties, where the value of `reason` is a string.

Tire does not depend on Q. tire.ajax will only use promises if Q has already been loaded (or if Q has been specified in an AMD environment). Otherwise, it will behave in its traditional manner.

### CODE REVIEW

**Comment by frozzare** [comment]
Thanks for your pull request, but I don't think this is the right way to go with Tire. Earlier version of Tire did have support for AMD and if I don't remember wrong it have support for Sizzle (if Sizzle was loaded before Tire) but we removed both AMD support and Sizzle support because we wanted a JavaScript framework that din't have special code in the core for stuff that maybe didn't exists in your project. (It also reduce file size a bit).

You could have a own fork that has this support and we could have it up on the site, like in a new section that lists special builds of Tire or something like that. I'm open for discussions about this.

Haven't looked so much at the tests but your commit breaks all tests and that's not good ;)

**Comment by smcmurray** [comment]
This isn't support for AMD, it's promises support for ajax.

I think it is questionable to have basic API behavior change depending on what other js code might exist in the environment. That could be a valid reason to reject this pull request.

But it might be worth it, especially if it is a documented aspect of the one/two API methods it affects.

Getting promise support with only a few bytes of code is appealing to me.

Breaking tests is bad, of course. Perhaps the latest commit here fixes that?

**Comment by smcmurray** [comment]
Oh. I forgot to mention: this also gives you progress notifications for promises.

**Comment by frozzare** [comment]
Didn't say that this was support for AMD. Used AMD as example for what we haved and what we removed from Tire.  I think I will reject this pull request for now, would love the se a fork that support this and maybe in the feature add support for promise. I trying to use stuff that already exists the browsers and promise aren't that supported yet. So I think is bad to select one promise library over another. 

The tests failed again, looks like it can't build the minified tire dist.

**Pull request closed without merging**
